# Generated by Django 4.1.6 on 2023-02-12 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking", old_name="conctact", new_name="contact",
        ),
    ]
